export const rows = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    phone: "123-456-7890",
    access: "Admin",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 25,
    phone: "123-456-7891",
    access: "User",
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    phone: "123-456-7892",
    access: "Manager",
  },
  {
    id: 4,
    name: "Bob Brown",
    email: "bob.brown@example.com",
    age: 40,
    phone: "123-456-7893",
    access: "Admin",
  },
  {
    id: 5,
    name: "Charlie Davis",
    email: "charlie.davis@example.com",
    age: 28,
    phone: "123-456-7894",
    access: "User",
  },
  {
    id: 6,
    name: "Dana White",
    email: "dana.white@example.com",
    age: 32,
    phone: "123-456-7895",
    access: "Manager",
  },
  {
    id: 7,
    name: "Eve Green",
    email: "eve.green@example.com",
    age: 45,
    phone: "123-456-7896",
    access: "User",
  },
  {
    id: 8,
    name: "Frank Black",
    email: "frank.black@example.com",
    age: 29,
    phone: "123-456-7897",
    access: "User",
  },
  {
    id: 9,
    name: "Grace Blue",
    email: "grace.blue@example.com",
    age: 33,
    phone: "123-456-7898",
    access: "User",
  },
];
